### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by The-Futurist** [rahulsahay19/MovieReviewStarterKit#1]
I just forked and cloned this hoping to play around and learn something but it will not build. 

e.g.

* One or more packages are incompatible with .NETFramework,Version=v4.0.

I cloned this at commit A9822494 and opened it in Visual Studio 2017.

If I open and try to build in VS 2015, I get other serious build errors:

e.g.

* The OutputPath property is not set for project 'MovieReviewStarterKit.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  
* This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.

There's something very wrong and so the repo is pretty much of no use.

Thanks

**Comment by rahulsahay19** [comment]
Project is working fine for me in both the version of VS. However, this is basic stuff, you can't go back from higher to lower version. So, if you would have opened the solution first in VS-2107, then it won't work with VS-2015 as project compatibilities differ from solution to solution. You can download the completed project from this url https://github.com/rahulsahay19/Movie-Review-SPA. Recommended way to open the project in 2015 as I have written completely in that VS. This project is live since 10 months and so far no issue raised!
